server:
  port: 8080

marklogic:
  host: localhost
  port: 9090 # MarkLogic REST API server port (default 8000)
  username: admin
  password: admin

spring:
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

logging:
  level:
    com.datainsights: INFO
